CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE SCHEMA extensions; CREATE EXTENSION pgcrypto WITH SCHEMA extensions;
CREATE SCHEMA net;
CREATE FUNCTION net.http_post(url text,headers jsonb,body jsonb,timeout_milliseconds integer) RETURNS bigint LANGUAGE sql AS 'SELECT 1::bigint';
CREATE SCHEMA cron; CREATE TABLE cron.job(jobid bigint GENERATED BY DEFAULT AS IDENTITY,jobname text,active boolean);
CREATE FUNCTION cron.schedule(text,text,text) RETURNS bigint LANGUAGE sql AS 'INSERT INTO cron.job(jobname,active) VALUES($1,true) RETURNING jobid';
CREATE FUNCTION cron.alter_job(bigint,active boolean) RETURNS void LANGUAGE sql AS 'UPDATE cron.job SET active=$2 WHERE jobid=$1';
CREATE TABLE editorial_admin_memberships(user_id uuid PRIMARY KEY,role text,active boolean);
