/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscolherbikeRouteImport } from './routes/escolherbike'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as GrupodeofertasRouteImport } from './routes/grupodeofertas'
import { Route as PainelBikesRouteImport } from './routes/painel-bikes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AcompanhamentoIndexRouteImport } from './routes/acompanhamento/index'
import { Route as AcompanhamentoBikeIdRouteImport } from './routes/acompanhamento/$bikeId'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBikesRouteImport } from './routes/admin/bikes'
import { Route as AdminGrowthRouteImport } from './routes/admin/growth'
import { Route as AdminIaRouteImport } from './routes/admin/ia'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminVideosRouteImport } from './routes/admin/videos'
import { Route as BikesIndexRouteImport } from './routes/bikes/index'
import { Route as BikesSlugRouteImport } from './routes/bikes/$slug'
import { Route as CalculadorasCarroVsBikeRouteImport } from './routes/calculadoras/carro-vs-bike'
import { Route as CalculadorasCustoAnualMobilidadeRouteImport } from './routes/calculadoras/custo-anual-mobilidade'
import { Route as CalculadorasEconomiaRouteImport } from './routes/calculadoras/economia'
import { Route as CalculadorasMotoVsBikeRouteImport } from './routes/calculadoras/moto-vs-bike'
import { Route as CalculadorasPaybackRouteImport } from './routes/calculadoras/payback'
import { Route as CalculadorasTempoNoTransitoRouteImport } from './routes/calculadoras/tempo-no-transito'
import { Route as CalculadorasTempoRecuperadoRouteImport } from './routes/calculadoras/tempo-recuperado'
import { Route as CalculadorasTransportePublicoVsBikeRouteImport } from './routes/calculadoras/transporte-publico-vs-bike'
import { Route as CalculadorasUberVsBikeRouteImport } from './routes/calculadoras/uber-vs-bike'
import { Route as ConteudosIndexRouteImport } from './routes/conteudos/index'
import { Route as ConteudosSlugRouteImport } from './routes/conteudos/$slug'
import { Route as RadarIndexRouteImport } from './routes/radar/index'
import { Route as RadarBikeIdRouteImport } from './routes/radar/$bikeId'
import { Route as AdminConteudosIndexRouteImport } from './routes/admin/conteudos/index'
import { Route as AdminConteudosIdRouteImport } from './routes/admin/conteudos/$id'
import { Route as AdminConteudosNovoRouteImport } from './routes/admin/conteudos/novo'
import { Route as AdminConteudosIdPreviewRouteImport } from './routes/admin/conteudos/$id/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherbikeRoute = EscolherbikeRouteImport.update({
  id: '/escolherbike',
  path: '/escolherbike',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupodeofertasRoute = GrupodeofertasRouteImport.update({
  id: '/grupodeofertas',
  path: '/grupodeofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelBikesRoute = PainelBikesRouteImport.update({
  id: '/painel-bikes',
  path: '/painel-bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoIndexRoute = AcompanhamentoIndexRouteImport.update({
  id: '/acompanhamento/',
  path: '/acompanhamento/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoBikeIdRoute = AcompanhamentoBikeIdRouteImport.update({
  id: '/acompanhamento/$bikeId',
  path: '/acompanhamento/$bikeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBikesRoute = AdminBikesRouteImport.update({
  id: '/admin/bikes',
  path: '/admin/bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGrowthRoute = AdminGrowthRouteImport.update({
  id: '/admin/growth',
  path: '/admin/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/admin/ia',
  path: '/admin/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesIndexRoute = BikesIndexRouteImport.update({
  id: '/bikes/',
  path: '/bikes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesSlugRoute = BikesSlugRouteImport.update({
  id: '/bikes/$slug',
  path: '/bikes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasCarroVsBikeRoute = CalculadorasCarroVsBikeRouteImport.update({
  id: '/calculadoras/carro-vs-bike',
  path: '/calculadoras/carro-vs-bike',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasCustoAnualMobilidadeRoute =
  CalculadorasCustoAnualMobilidadeRouteImport.update({
    id: '/calculadoras/custo-anual-mobilidade',
    path: '/calculadoras/custo-anual-mobilidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasEconomiaRoute = CalculadorasEconomiaRouteImport.update({
  id: '/calculadoras/economia',
  path: '/calculadoras/economia',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasMotoVsBikeRoute = CalculadorasMotoVsBikeRouteImport.update({
  id: '/calculadoras/moto-vs-bike',
  path: '/calculadoras/moto-vs-bike',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasPaybackRoute = CalculadorasPaybackRouteImport.update({
  id: '/calculadoras/payback',
  path: '/calculadoras/payback',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasTempoNoTransitoRoute =
  CalculadorasTempoNoTransitoRouteImport.update({
    id: '/calculadoras/tempo-no-transito',
    path: '/calculadoras/tempo-no-transito',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasTempoRecuperadoRoute =
  CalculadorasTempoRecuperadoRouteImport.update({
    id: '/calculadoras/tempo-recuperado',
    path: '/calculadoras/tempo-recuperado',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasTransportePublicoVsBikeRoute =
  CalculadorasTransportePublicoVsBikeRouteImport.update({
    id: '/calculadoras/transporte-publico-vs-bike',
    path: '/calculadoras/transporte-publico-vs-bike',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalculadorasUberVsBikeRoute = CalculadorasUberVsBikeRouteImport.update({
  id: '/calculadoras/uber-vs-bike',
  path: '/calculadoras/uber-vs-bike',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosIndexRoute = ConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosSlugRoute = ConteudosSlugRouteImport.update({
  id: '/conteudos/$slug',
  path: '/conteudos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarIndexRoute = RadarIndexRouteImport.update({
  id: '/radar/',
  path: '/radar/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarBikeIdRoute = RadarBikeIdRouteImport.update({
  id: '/radar/$bikeId',
  path: '/radar/$bikeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosIndexRoute = AdminConteudosIndexRouteImport.update({
  id: '/admin/conteudos/',
  path: '/admin/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosIdRoute = AdminConteudosIdRouteImport.update({
  id: '/admin/conteudos/$id',
  path: '/admin/conteudos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosNovoRoute = AdminConteudosNovoRouteImport.update({
  id: '/admin/conteudos/novo',
  path: '/admin/conteudos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosIdPreviewRoute = AdminConteudosIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminConteudosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escolherbike': typeof EscolherbikeRoute
  '/ferramentas': typeof FerramentasRoute
  '/grupodeofertas': typeof GrupodeofertasRoute
  '/painel-bikes': typeof PainelBikesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acompanhamento/$bikeId': typeof AcompanhamentoBikeIdRoute
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/bikes/$slug': typeof BikesSlugRoute
  '/calculadoras/carro-vs-bike': typeof CalculadorasCarroVsBikeRoute
  '/calculadoras/custo-anual-mobilidade': typeof CalculadorasCustoAnualMobilidadeRoute
  '/calculadoras/economia': typeof CalculadorasEconomiaRoute
  '/calculadoras/moto-vs-bike': typeof CalculadorasMotoVsBikeRoute
  '/calculadoras/payback': typeof CalculadorasPaybackRoute
  '/calculadoras/tempo-no-transito': typeof CalculadorasTempoNoTransitoRoute
  '/calculadoras/tempo-recuperado': typeof CalculadorasTempoRecuperadoRoute
  '/calculadoras/transporte-publico-vs-bike': typeof CalculadorasTransportePublicoVsBikeRoute
  '/calculadoras/uber-vs-bike': typeof CalculadorasUberVsBikeRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/radar/$bikeId': typeof RadarBikeIdRoute
  '/acompanhamento/': typeof AcompanhamentoIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/bikes/': typeof BikesIndexRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/radar/': typeof RadarIndexRoute
  '/admin/conteudos/$id': typeof AdminConteudosIdRouteWithChildren
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/conteudos/': typeof AdminConteudosIndexRoute
  '/admin/conteudos/$id/preview': typeof AdminConteudosIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/escolherbike': typeof EscolherbikeRoute
  '/ferramentas': typeof FerramentasRoute
  '/grupodeofertas': typeof GrupodeofertasRoute
  '/painel-bikes': typeof PainelBikesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acompanhamento/$bikeId': typeof AcompanhamentoBikeIdRoute
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/bikes/$slug': typeof BikesSlugRoute
  '/calculadoras/carro-vs-bike': typeof CalculadorasCarroVsBikeRoute
  '/calculadoras/custo-anual-mobilidade': typeof CalculadorasCustoAnualMobilidadeRoute
  '/calculadoras/economia': typeof CalculadorasEconomiaRoute
  '/calculadoras/moto-vs-bike': typeof CalculadorasMotoVsBikeRoute
  '/calculadoras/payback': typeof CalculadorasPaybackRoute
  '/calculadoras/tempo-no-transito': typeof CalculadorasTempoNoTransitoRoute
  '/calculadoras/tempo-recuperado': typeof CalculadorasTempoRecuperadoRoute
  '/calculadoras/transporte-publico-vs-bike': typeof CalculadorasTransportePublicoVsBikeRoute
  '/calculadoras/uber-vs-bike': typeof CalculadorasUberVsBikeRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/radar/$bikeId': typeof RadarBikeIdRoute
  '/acompanhamento': typeof AcompanhamentoIndexRoute
  '/admin': typeof AdminIndexRoute
  '/bikes': typeof BikesIndexRoute
  '/conteudos': typeof ConteudosIndexRoute
  '/radar': typeof RadarIndexRoute
  '/admin/conteudos/$id': typeof AdminConteudosIdRouteWithChildren
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/conteudos': typeof AdminConteudosIndexRoute
  '/admin/conteudos/$id/preview': typeof AdminConteudosIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/escolherbike': typeof EscolherbikeRoute
  '/ferramentas': typeof FerramentasRoute
  '/grupodeofertas': typeof GrupodeofertasRoute
  '/painel-bikes': typeof PainelBikesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/acompanhamento/$bikeId': typeof AcompanhamentoBikeIdRoute
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/growth': typeof AdminGrowthRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/bikes/$slug': typeof BikesSlugRoute
  '/calculadoras/carro-vs-bike': typeof CalculadorasCarroVsBikeRoute
  '/calculadoras/custo-anual-mobilidade': typeof CalculadorasCustoAnualMobilidadeRoute
  '/calculadoras/economia': typeof CalculadorasEconomiaRoute
  '/calculadoras/moto-vs-bike': typeof CalculadorasMotoVsBikeRoute
  '/calculadoras/payback': typeof CalculadorasPaybackRoute
  '/calculadoras/tempo-no-transito': typeof CalculadorasTempoNoTransitoRoute
  '/calculadoras/tempo-recuperado': typeof CalculadorasTempoRecuperadoRoute
  '/calculadoras/transporte-publico-vs-bike': typeof CalculadorasTransportePublicoVsBikeRoute
  '/calculadoras/uber-vs-bike': typeof CalculadorasUberVsBikeRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/radar/$bikeId': typeof RadarBikeIdRoute
  '/acompanhamento/': typeof AcompanhamentoIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/bikes/': typeof BikesIndexRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/radar/': typeof RadarIndexRoute
  '/admin/conteudos/$id': typeof AdminConteudosIdRouteWithChildren
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/conteudos/': typeof AdminConteudosIndexRoute
  '/admin/conteudos/$id/preview': typeof AdminConteudosIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/escolherbike'
    | '/ferramentas'
    | '/grupodeofertas'
    | '/painel-bikes'
    | '/sitemap.xml'
    | '/acompanhamento/$bikeId'
    | '/admin/bikes'
    | '/admin/growth'
    | '/admin/ia'
    | '/admin/logs'
    | '/admin/videos'
    | '/bikes/$slug'
    | '/calculadoras/carro-vs-bike'
    | '/calculadoras/custo-anual-mobilidade'
    | '/calculadoras/economia'
    | '/calculadoras/moto-vs-bike'
    | '/calculadoras/payback'
    | '/calculadoras/tempo-no-transito'
    | '/calculadoras/tempo-recuperado'
    | '/calculadoras/transporte-publico-vs-bike'
    | '/calculadoras/uber-vs-bike'
    | '/conteudos/$slug'
    | '/radar/$bikeId'
    | '/acompanhamento/'
    | '/admin/'
    | '/bikes/'
    | '/conteudos/'
    | '/radar/'
    | '/admin/conteudos/$id'
    | '/admin/conteudos/novo'
    | '/admin/conteudos/'
    | '/admin/conteudos/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/escolherbike'
    | '/ferramentas'
    | '/grupodeofertas'
    | '/painel-bikes'
    | '/sitemap.xml'
    | '/acompanhamento/$bikeId'
    | '/admin/bikes'
    | '/admin/growth'
    | '/admin/ia'
    | '/admin/logs'
    | '/admin/videos'
    | '/bikes/$slug'
    | '/calculadoras/carro-vs-bike'
    | '/calculadoras/custo-anual-mobilidade'
    | '/calculadoras/economia'
    | '/calculadoras/moto-vs-bike'
    | '/calculadoras/payback'
    | '/calculadoras/tempo-no-transito'
    | '/calculadoras/tempo-recuperado'
    | '/calculadoras/transporte-publico-vs-bike'
    | '/calculadoras/uber-vs-bike'
    | '/conteudos/$slug'
    | '/radar/$bikeId'
    | '/acompanhamento'
    | '/admin'
    | '/bikes'
    | '/conteudos'
    | '/radar'
    | '/admin/conteudos/$id'
    | '/admin/conteudos/novo'
    | '/admin/conteudos'
    | '/admin/conteudos/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/escolherbike'
    | '/ferramentas'
    | '/grupodeofertas'
    | '/painel-bikes'
    | '/sitemap.xml'
    | '/acompanhamento/$bikeId'
    | '/admin/bikes'
    | '/admin/growth'
    | '/admin/ia'
    | '/admin/logs'
    | '/admin/videos'
    | '/bikes/$slug'
    | '/calculadoras/carro-vs-bike'
    | '/calculadoras/custo-anual-mobilidade'
    | '/calculadoras/economia'
    | '/calculadoras/moto-vs-bike'
    | '/calculadoras/payback'
    | '/calculadoras/tempo-no-transito'
    | '/calculadoras/tempo-recuperado'
    | '/calculadoras/transporte-publico-vs-bike'
    | '/calculadoras/uber-vs-bike'
    | '/conteudos/$slug'
    | '/radar/$bikeId'
    | '/acompanhamento/'
    | '/admin/'
    | '/bikes/'
    | '/conteudos/'
    | '/radar/'
    | '/admin/conteudos/$id'
    | '/admin/conteudos/novo'
    | '/admin/conteudos/'
    | '/admin/conteudos/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EscolherbikeRoute: typeof EscolherbikeRoute
  FerramentasRoute: typeof FerramentasRoute
  GrupodeofertasRoute: typeof GrupodeofertasRoute
  PainelBikesRoute: typeof PainelBikesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AcompanhamentoBikeIdRoute: typeof AcompanhamentoBikeIdRoute
  AdminBikesRoute: typeof AdminBikesRoute
  AdminGrowthRoute: typeof AdminGrowthRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  BikesSlugRoute: typeof BikesSlugRoute
  CalculadorasCarroVsBikeRoute: typeof CalculadorasCarroVsBikeRoute
  CalculadorasCustoAnualMobilidadeRoute: typeof CalculadorasCustoAnualMobilidadeRoute
  CalculadorasEconomiaRoute: typeof CalculadorasEconomiaRoute
  CalculadorasMotoVsBikeRoute: typeof CalculadorasMotoVsBikeRoute
  CalculadorasPaybackRoute: typeof CalculadorasPaybackRoute
  CalculadorasTempoNoTransitoRoute: typeof CalculadorasTempoNoTransitoRoute
  CalculadorasTempoRecuperadoRoute: typeof CalculadorasTempoRecuperadoRoute
  CalculadorasTransportePublicoVsBikeRoute: typeof CalculadorasTransportePublicoVsBikeRoute
  CalculadorasUberVsBikeRoute: typeof CalculadorasUberVsBikeRoute
  ConteudosSlugRoute: typeof ConteudosSlugRoute
  RadarBikeIdRoute: typeof RadarBikeIdRoute
  AcompanhamentoIndexRoute: typeof AcompanhamentoIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BikesIndexRoute: typeof BikesIndexRoute
  ConteudosIndexRoute: typeof ConteudosIndexRoute
  RadarIndexRoute: typeof RadarIndexRoute
  AdminConteudosIdRoute: typeof AdminConteudosIdRouteWithChildren
  AdminConteudosNovoRoute: typeof AdminConteudosNovoRoute
  AdminConteudosIndexRoute: typeof AdminConteudosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolherbike': {
      id: '/escolherbike'
      path: '/escolherbike'
      fullPath: '/escolherbike'
      preLoaderRoute: typeof EscolherbikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupodeofertas': {
      id: '/grupodeofertas'
      path: '/grupodeofertas'
      fullPath: '/grupodeofertas'
      preLoaderRoute: typeof GrupodeofertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-bikes': {
      id: '/painel-bikes'
      path: '/painel-bikes'
      fullPath: '/painel-bikes'
      preLoaderRoute: typeof PainelBikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento/': {
      id: '/acompanhamento/'
      path: '/acompanhamento'
      fullPath: '/acompanhamento/'
      preLoaderRoute: typeof AcompanhamentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento/$bikeId': {
      id: '/acompanhamento/$bikeId'
      path: '/acompanhamento/$bikeId'
      fullPath: '/acompanhamento/$bikeId'
      preLoaderRoute: typeof AcompanhamentoBikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bikes': {
      id: '/admin/bikes'
      path: '/admin/bikes'
      fullPath: '/admin/bikes'
      preLoaderRoute: typeof AdminBikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/growth': {
      id: '/admin/growth'
      path: '/admin/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AdminGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/admin/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/': {
      id: '/bikes/'
      path: '/bikes'
      fullPath: '/bikes/'
      preLoaderRoute: typeof BikesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/$slug': {
      id: '/bikes/$slug'
      path: '/bikes/$slug'
      fullPath: '/bikes/$slug'
      preLoaderRoute: typeof BikesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/carro-vs-bike': {
      id: '/calculadoras/carro-vs-bike'
      path: '/calculadoras/carro-vs-bike'
      fullPath: '/calculadoras/carro-vs-bike'
      preLoaderRoute: typeof CalculadorasCarroVsBikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/custo-anual-mobilidade': {
      id: '/calculadoras/custo-anual-mobilidade'
      path: '/calculadoras/custo-anual-mobilidade'
      fullPath: '/calculadoras/custo-anual-mobilidade'
      preLoaderRoute: typeof CalculadorasCustoAnualMobilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/economia': {
      id: '/calculadoras/economia'
      path: '/calculadoras/economia'
      fullPath: '/calculadoras/economia'
      preLoaderRoute: typeof CalculadorasEconomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/moto-vs-bike': {
      id: '/calculadoras/moto-vs-bike'
      path: '/calculadoras/moto-vs-bike'
      fullPath: '/calculadoras/moto-vs-bike'
      preLoaderRoute: typeof CalculadorasMotoVsBikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/payback': {
      id: '/calculadoras/payback'
      path: '/calculadoras/payback'
      fullPath: '/calculadoras/payback'
      preLoaderRoute: typeof CalculadorasPaybackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/tempo-no-transito': {
      id: '/calculadoras/tempo-no-transito'
      path: '/calculadoras/tempo-no-transito'
      fullPath: '/calculadoras/tempo-no-transito'
      preLoaderRoute: typeof CalculadorasTempoNoTransitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/tempo-recuperado': {
      id: '/calculadoras/tempo-recuperado'
      path: '/calculadoras/tempo-recuperado'
      fullPath: '/calculadoras/tempo-recuperado'
      preLoaderRoute: typeof CalculadorasTempoRecuperadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/transporte-publico-vs-bike': {
      id: '/calculadoras/transporte-publico-vs-bike'
      path: '/calculadoras/transporte-publico-vs-bike'
      fullPath: '/calculadoras/transporte-publico-vs-bike'
      preLoaderRoute: typeof CalculadorasTransportePublicoVsBikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras/uber-vs-bike': {
      id: '/calculadoras/uber-vs-bike'
      path: '/calculadoras/uber-vs-bike'
      fullPath: '/calculadoras/uber-vs-bike'
      preLoaderRoute: typeof CalculadorasUberVsBikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/': {
      id: '/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof ConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/$slug': {
      id: '/conteudos/$slug'
      path: '/conteudos/$slug'
      fullPath: '/conteudos/$slug'
      preLoaderRoute: typeof ConteudosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/': {
      id: '/radar/'
      path: '/radar'
      fullPath: '/radar/'
      preLoaderRoute: typeof RadarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/$bikeId': {
      id: '/radar/$bikeId'
      path: '/radar/$bikeId'
      fullPath: '/radar/$bikeId'
      preLoaderRoute: typeof RadarBikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/': {
      id: '/admin/conteudos/'
      path: '/admin/conteudos'
      fullPath: '/admin/conteudos/'
      preLoaderRoute: typeof AdminConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/$id': {
      id: '/admin/conteudos/$id'
      path: '/admin/conteudos/$id'
      fullPath: '/admin/conteudos/$id'
      preLoaderRoute: typeof AdminConteudosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/novo': {
      id: '/admin/conteudos/novo'
      path: '/admin/conteudos/novo'
      fullPath: '/admin/conteudos/novo'
      preLoaderRoute: typeof AdminConteudosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/$id/preview': {
      id: '/admin/conteudos/$id/preview'
      path: '/preview'
      fullPath: '/admin/conteudos/$id/preview'
      preLoaderRoute: typeof AdminConteudosIdPreviewRouteImport
      parentRoute: typeof AdminConteudosIdRoute
    }
  }
}

interface AdminConteudosIdRouteChildren {
  AdminConteudosIdPreviewRoute: typeof AdminConteudosIdPreviewRoute
}

const AdminConteudosIdRouteChildren: AdminConteudosIdRouteChildren = {
  AdminConteudosIdPreviewRoute: AdminConteudosIdPreviewRoute,
}

const AdminConteudosIdRouteWithChildren =
  AdminConteudosIdRoute._addFileChildren(AdminConteudosIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EscolherbikeRoute: EscolherbikeRoute,
  FerramentasRoute: FerramentasRoute,
  GrupodeofertasRoute: GrupodeofertasRoute,
  PainelBikesRoute: PainelBikesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AcompanhamentoBikeIdRoute: AcompanhamentoBikeIdRoute,
  AdminBikesRoute: AdminBikesRoute,
  AdminGrowthRoute: AdminGrowthRoute,
  AdminIaRoute: AdminIaRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminVideosRoute: AdminVideosRoute,
  BikesSlugRoute: BikesSlugRoute,
  CalculadorasCarroVsBikeRoute: CalculadorasCarroVsBikeRoute,
  CalculadorasCustoAnualMobilidadeRoute: CalculadorasCustoAnualMobilidadeRoute,
  CalculadorasEconomiaRoute: CalculadorasEconomiaRoute,
  CalculadorasMotoVsBikeRoute: CalculadorasMotoVsBikeRoute,
  CalculadorasPaybackRoute: CalculadorasPaybackRoute,
  CalculadorasTempoNoTransitoRoute: CalculadorasTempoNoTransitoRoute,
  CalculadorasTempoRecuperadoRoute: CalculadorasTempoRecuperadoRoute,
  CalculadorasTransportePublicoVsBikeRoute:
    CalculadorasTransportePublicoVsBikeRoute,
  CalculadorasUberVsBikeRoute: CalculadorasUberVsBikeRoute,
  ConteudosSlugRoute: ConteudosSlugRoute,
  RadarBikeIdRoute: RadarBikeIdRoute,
  AcompanhamentoIndexRoute: AcompanhamentoIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  BikesIndexRoute: BikesIndexRoute,
  ConteudosIndexRoute: ConteudosIndexRoute,
  RadarIndexRoute: RadarIndexRoute,
  AdminConteudosIdRoute: AdminConteudosIdRouteWithChildren,
  AdminConteudosNovoRoute: AdminConteudosNovoRoute,
  AdminConteudosIndexRoute: AdminConteudosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
