/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscolherbikeRouteImport } from './routes/escolherbike'
import { Route as GrupodeofertasRouteImport } from './routes/grupodeofertas'
import { Route as PainelBikesRouteImport } from './routes/painel-bikes'
import { Route as AcompanhamentoIndexRouteImport } from './routes/acompanhamento/index'
import { Route as AcompanhamentoBikeIdRouteImport } from './routes/acompanhamento/$bikeId'
import { Route as BikesIndexRouteImport } from './routes/bikes/index'
import { Route as BikesSlugRouteImport } from './routes/bikes/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherbikeRoute = EscolherbikeRouteImport.update({
  id: '/escolherbike',
  path: '/escolherbike',
  getParentRoute: () => rootRouteImport,
} as any)
const GrupodeofertasRoute = GrupodeofertasRouteImport.update({
  id: '/grupodeofertas',
  path: '/grupodeofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelBikesRoute = PainelBikesRouteImport.update({
  id: '/painel-bikes',
  path: '/painel-bikes',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoIndexRoute = AcompanhamentoIndexRouteImport.update({
  id: '/acompanhamento/',
  path: '/acompanhamento/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanhamentoBikeIdRoute = AcompanhamentoBikeIdRouteImport.update({
  id: '/acompanhamento/$bikeId',
  path: '/acompanhamento/$bikeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesIndexRoute = BikesIndexRouteImport.update({
  id: '/bikes/',
  path: '/bikes/',
  getParentRoute: () => rootRouteImport,
} as any)
const BikesSlugRoute = BikesSlugRouteImport.update({
  id: '/bikes/$slug',
  path: '/bikes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escolherbike': typeof EscolherbikeRoute
  '/grupodeofertas': typeof GrupodeofertasRoute
  '/painel-bikes': typeof PainelBikesRoute
  '/acompanhamento/$bikeId': typeof AcompanhamentoBikeIdRoute
  '/bikes/$slug': typeof BikesSlugRoute
  '/acompanhamento/': typeof AcompanhamentoIndexRoute
  '/bikes/': typeof BikesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/escolherbike': typeof EscolherbikeRoute
  '/grupodeofertas': typeof GrupodeofertasRoute
  '/painel-bikes': typeof PainelBikesRoute
  '/acompanhamento/$bikeId': typeof AcompanhamentoBikeIdRoute
  '/bikes/$slug': typeof BikesSlugRoute
  '/acompanhamento': typeof AcompanhamentoIndexRoute
  '/bikes': typeof BikesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/escolherbike': typeof EscolherbikeRoute
  '/grupodeofertas': typeof GrupodeofertasRoute
  '/painel-bikes': typeof PainelBikesRoute
  '/acompanhamento/$bikeId': typeof AcompanhamentoBikeIdRoute
  '/bikes/$slug': typeof BikesSlugRoute
  '/acompanhamento/': typeof AcompanhamentoIndexRoute
  '/bikes/': typeof BikesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/escolherbike'
    | '/grupodeofertas'
    | '/painel-bikes'
    | '/acompanhamento/$bikeId'
    | '/bikes/$slug'
    | '/acompanhamento/'
    | '/bikes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/escolherbike'
    | '/grupodeofertas'
    | '/painel-bikes'
    | '/acompanhamento/$bikeId'
    | '/bikes/$slug'
    | '/acompanhamento'
    | '/bikes'
  id:
    | '__root__'
    | '/'
    | '/escolherbike'
    | '/grupodeofertas'
    | '/painel-bikes'
    | '/acompanhamento/$bikeId'
    | '/bikes/$slug'
    | '/acompanhamento/'
    | '/bikes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EscolherbikeRoute: typeof EscolherbikeRoute
  GrupodeofertasRoute: typeof GrupodeofertasRoute
  PainelBikesRoute: typeof PainelBikesRoute
  AcompanhamentoBikeIdRoute: typeof AcompanhamentoBikeIdRoute
  BikesSlugRoute: typeof BikesSlugRoute
  AcompanhamentoIndexRoute: typeof AcompanhamentoIndexRoute
  BikesIndexRoute: typeof BikesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolherbike': {
      id: '/escolherbike'
      path: '/escolherbike'
      fullPath: '/escolherbike'
      preLoaderRoute: typeof EscolherbikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupodeofertas': {
      id: '/grupodeofertas'
      path: '/grupodeofertas'
      fullPath: '/grupodeofertas'
      preLoaderRoute: typeof GrupodeofertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-bikes': {
      id: '/painel-bikes'
      path: '/painel-bikes'
      fullPath: '/painel-bikes'
      preLoaderRoute: typeof PainelBikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento/': {
      id: '/acompanhamento/'
      path: '/acompanhamento'
      fullPath: '/acompanhamento/'
      preLoaderRoute: typeof AcompanhamentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhamento/$bikeId': {
      id: '/acompanhamento/$bikeId'
      path: '/acompanhamento/$bikeId'
      fullPath: '/acompanhamento/$bikeId'
      preLoaderRoute: typeof AcompanhamentoBikeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/': {
      id: '/bikes/'
      path: '/bikes'
      fullPath: '/bikes/'
      preLoaderRoute: typeof BikesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bikes/$slug': {
      id: '/bikes/$slug'
      path: '/bikes/$slug'
      fullPath: '/bikes/$slug'
      preLoaderRoute: typeof BikesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EscolherbikeRoute: EscolherbikeRoute,
  GrupodeofertasRoute: GrupodeofertasRoute,
  PainelBikesRoute: PainelBikesRoute,
  AcompanhamentoBikeIdRoute: AcompanhamentoBikeIdRoute,
  BikesSlugRoute: BikesSlugRoute,
  AcompanhamentoIndexRoute: AcompanhamentoIndexRoute,
  BikesIndexRoute: BikesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
